baseURL: "https://zhijianli9999.github.io"
title: Zhijian Li
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: research/
          weight: 2
        - CV
          url: li_cv_101424.pdf
          weight: 2
params:
    description: "This website hosts Zhijian Li's research papers, books, course materials, data, curriculum vitae, and contact information."
    author: Zhijian Li
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["research", "cv", "misc"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Zhijian Li
          subtitle: "Hi! I'm a PhD student in Quantitative Marketing at Northwestern University's Kellogg School of Management. My research interest lies mainly in empirical industrial organization. Before this, I was a research assistant at UCLA Anderson School of Management. I was born in China, raised in Singapore, and got my Bachelor's in Mathematics-Economics and Master's in Economics at UCLA. I go by my last name, Li."
          imageUrl: "official photo kellogg.jpg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Research
              url: research/
            - name: CV
              url: li_cv_101424.pdf

    socialIcons:
        - name: CV
          url: li_cv_101424.pdf
        - name: Email
          url: mailto:zhijian.li@kellogg.northwestern.edu
        - name: Location
          url: location/
        - name: GitHub
          url: https://github.com/zhijianli9999
        - name: Twitter
          url: https://x.com/zhijian__li
        
    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Zhijian Li"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2